### ISSUE TITLE
Search Previews is not working!

### ISSUE THREAD

**Issue by davex2012** [fastaddons/SearchResultPreviews#17]
**Describe the bug**  
Serchpreview is not showing anymore!

Latest version of Firefox.
<img width="994" alt="Skjermbilde 2024-01-24 kl  18 11 52" src="https://github.com/fastaddons/SearchResultPreviews/assets/15570883/66fa04b2-caef-4006-9060-72df77084526">

**Comment by Juraj-Masiar** [comment]
Hello,
My VPS provider (Contabo) has network issues again, so the whole server is inaccessible:
https://srp.fastaddons.com
I've created a report in their system so let's hope they can fix it fast.
This happens every few months and usually they fix it in a few hours.

I have to say, Contabo is pretty terrible regarding stability and also support. 
But their prices are way lower then any more reliable competitors. 
And since this project requires hundreds of gigabytes of storage, it was the only one I could afford.

**Comment by Juraj-Masiar** [comment]
Seems like they've fixed the network issues. All should work fine now :)

**Comment by Juraj-Masiar** [comment]
I can't believe it's broken again... 
But this time the network works, but the SSD speed is like "non-existing" so all requests takes forever to complete.
I've contacted the support again but they are super slow replying.
What a bad luck :(

**Comment by davex2012** [comment]
Why can't i change filters? Enabled all and want to disable some page but cant do it why is that?

**Comment by Juraj-Masiar** [comment]
Once you enable on all pages, there is no turn back :), it's browser problem.
One way to fix it is to uninstall the addon and install it back (you may need to restart browser after uninstalling).

**Comment by Juraj-Masiar** [comment]
They are working on the fix:

![image](https://github.com/fastaddons/SearchResultPreviews/assets/6358971/b29ba1b2-be80-4a98-b737-ad158a3226db)

Currently the server works again but they wrote me they will look for the root cause so there may be more down time
