### ISSUE TITLE
Connects to google server when using startpage

### ISSUE THREAD

**Issue by citizenserious** [fastaddons/SearchResultPreviews#18]
**Describe the bug**  
![image](https://github.com/fastaddons/SearchResultPreviews/assets/62773866/86d755ba-4bbf-46fe-9c39-6fe8a56046ad)
Somehow ublock shows me a connection to google.com only with the add-on enabled.

**Steps To Reproduce**  
1. download the add on
2. search
3. The problem is that somehow it shows me a connection to google on startpage.

**Expected behavior**  
no connection to google
I tried it on duckduckgo there is no such behavior

**Device info:**
 - operating system: win 11
 - Browser and version: Firefox 122.0
 - "Search Result Previews" version: 3.6

**Additional info**
Add any other info about the problem here.

**Comment by Juraj-Masiar** [comment]
Hello,
First, let me say that currently my [addon server is unreachable](https://github.com/fastaddons/SearchResultPreviews/issues/17), my VPS provider has network issues in the cluster where my server is located, that's why it doesn't work.

Regarding Google connections, my addon is pulling page favicons from the Google servers, so if you have favicons enabled, then connection to Google is expected.
Some search providers are showing favicons automatically even without this addon, so for those there will be no google requests.

Note that you can change these settings, for example switch to Duck Duck Go favicon provider or disable them completely:
![image](https://github.com/fastaddons/SearchResultPreviews/assets/6358971/0d9527d7-17d0-4dd0-addf-fa930f9966eb)

**Comment by citizenserious** [comment]
Hey,
thanks for the quick reply and educating me. 
I was a bit worried that it could be a bug in relation to a connectivity check of some sort triggered by the connection loss to your server. Just noticed the google connection today, because I was wondering and trying to investigate why it's not working :D
I hope it will be up soon (:

Your add-on is just awesome work, sorry for bothering you.

**Comment by Juraj-Masiar** [comment]
Thanks :), and no problem.
I've wrote them another message asking them to move my server to a different server cluster, so let's see how fast is their support.
It's bothering me though because their server status page doesn't report any maintenance in my cluster:
https://contabo-status.com/
